const $=id=>document.getElementById(id);
const cvs=$("graph"),ctx=cvs.getContext("2d");
const E={a:$("a"),b:$("b"),c:$("c"),av:$("aValue"),bv:$("bValue"),cv:$("cValue"),dev:$("developed"),origin:$("origin"),fd:$("formDeveloped"),ff:$("formFactored"),fc:$("formCanonical"),delta:$("delta"),vertex:$("vertex"),axis:$("axis"),roots:$("roots")};
const fmt=n=>{if(!Number.isFinite(n))return"—";let r=Math.round(n*100)/100;return Number.isInteger(r)?String(r):String(r).replace(".",",")};
const term=(v,t)=>v===0?"":`${v>0?" + ":" − "}${Math.abs(v)===1&&t?"":fmt(Math.abs(v))}${t}`;
function developed(a,b,c){return `f(x) = ${a===1?"":a===-1?"−":fmt(a)}x²${term(b,"x")}${term(c,"")}`}
function model(){let a=+E.a.value,b=+E.b.value,c=+E.c.value;if(a===0){a=1;E.a.value=1}let d=b*b-4*a*c,alpha=-b/(2*a),beta=c-b*b/(4*a),roots=[];if(Math.abs(d)<1e-10)roots=[-b/(2*a)];else if(d>0)roots=[(-b-Math.sqrt(d))/(2*a),(-b+Math.sqrt(d))/(2*a)];return{a,b,c,d,alpha,beta,roots}}
function canonical(m){let ap=m.a===1?"":m.a===-1?"−":fmt(m.a),inside=Math.abs(m.alpha)<1e-10?"x":`x ${m.alpha>0?"−":"+"} ${fmt(Math.abs(m.alpha))}`,beta=Math.abs(m.beta)<1e-10?"":` ${m.beta>0?"+":"−"} ${fmt(Math.abs(m.beta))}`;return `f(x) = ${ap}(${inside})²${beta}`}
function factor(m){if(!m.roots.length)return"Pas de factorisation réelle";let ap=m.a===1?"":m.a===-1?"−":fmt(m.a),F=r=>`(x ${r>=0?"−":"+"} ${fmt(Math.abs(r))})`;return m.roots.length===1?`f(x) = ${ap}${F(m.roots[0])}²`:`f(x) = ${ap}${F(m.roots[0])}${F(m.roots[1])}`}
function update(){let m=model();E.av.textContent=m.a;E.bv.textContent=m.b;E.cv.textContent=m.c;E.dev.textContent=developed(m.a,m.b,m.c);E.origin.textContent=fmt(m.c);E.fd.textContent=developed(m.a,m.b,m.c);E.ff.textContent=factor(m);E.fc.textContent=canonical(m);E.delta.textContent=fmt(m.d);E.vertex.textContent=`S(${fmt(m.alpha)} ; ${fmt(m.beta)})`;E.axis.textContent=`x = ${fmt(m.alpha)}`;E.roots.textContent=!m.roots.length?"aucune réelle":m.roots.length===1?fmt(m.roots[0]):`${fmt(m.roots[0])} et ${fmt(m.roots[1])}`;draw(m)}
function draw(m){let W=cvs.width,H=cvs.height,xmin=-8,xmax=8,ymin=-12,ymax=12,X=x=>(x-xmin)/(xmax-xmin)*W,Y=y=>H-(y-ymin)/(ymax-ymin)*H;ctx.clearRect(0,0,W,H);ctx.fillStyle="#fff";ctx.fillRect(0,0,W,H);ctx.strokeStyle="#edf2f5";ctx.lineWidth=1;for(let x=-8;x<=8;x++){ctx.beginPath();ctx.moveTo(X(x),0);ctx.lineTo(X(x),H);ctx.stroke()}for(let y=-12;y<=12;y++){ctx.beginPath();ctx.moveTo(0,Y(y));ctx.lineTo(W,Y(y));ctx.stroke()}ctx.strokeStyle="#78909c";ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(X(0),0);ctx.lineTo(X(0),H);ctx.stroke();ctx.beginPath();ctx.moveTo(0,Y(0));ctx.lineTo(W,Y(0));ctx.stroke();ctx.strokeStyle="#0b78a8";ctx.lineWidth=4;ctx.beginPath();let started=false;for(let px=0;px<=W;px++){let x=xmin+px/W*(xmax-xmin),y=m.a*x*x+m.b*x+m.c,py=Y(y);if(py>-1000&&py<H+1000){if(!started){ctx.moveTo(px,py);started=true}else ctx.lineTo(px,py)}}ctx.stroke();point(X(m.alpha),Y(m.beta),"#26935c",7);m.roots.forEach(r=>point(X(r),Y(0),"#f58220",7));point(X(0),Y(m.c),"#c83f49",6)}
function point(x,y,color,r){if(y<0||y>cvs.height)return;ctx.fillStyle=color;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();ctx.strokeStyle="#fff";ctx.lineWidth=2;ctx.stroke()}
["a","b","c"].forEach(k=>E[k].addEventListener("input",update));
document.querySelectorAll("[data-preset]").forEach(b=>b.onclick=()=>{if(b.dataset.preset==="classic"){E.a.value=1;E.b.value=-4;E.c.value=3}if(b.dataset.preset==="double"){E.a.value=1;E.b.value=-6;E.c.value=9}if(b.dataset.preset==="none"){E.a.value=1;E.b.value=2;E.c.value=5}update()});
const ans={developpee:"Forme développée : f(0)=c est visible directement.",factorisee:"Forme factorisée : les racines et le signe sont les plus lisibles.",canonique:"Forme canonique : le sommet et l'extremum sont immédiatement lisibles."};
document.querySelectorAll("[data-answer]").forEach(b=>b.onclick=()=>$("strategyAnswer").textContent=ans[b.dataset.answer]);
const Q=[
{q:"Je veux connaître les racines de f. Quelle forme est la plus efficace ?",a:"Factorisée",o:["Développée","Factorisée","Canonique"],w:"La forme factorisée fait apparaître les zéros directement."},
{q:"Je veux lire le sommet. Quelle forme choisir ?",a:"Canonique",o:["Factorisée","Canonique","Développée"],w:"Dans a(x−α)²+β, le sommet est S(α ; β)."},
{q:"Je veux connaître immédiatement f(0). Quelle forme est la plus directe ?",a:"Développée",o:["Canonique","Factorisée","Développée"],w:"Dans ax²+bx+c, f(0)=c."},
{q:"Pour x²−9, que tester avant Δ ?",a:"Identité remarquable",o:["Discriminant","Identité remarquable","Forme canonique"],w:"x²−9=x²−3²=(x−3)(x+3)."},
{q:"Le trinôme est déjà factorisé et je veux son signe. Dois-je calculer Δ ?",a:"Non",o:["Oui","Non","Toujours"],w:"Les facteurs et leurs zéros suffisent."}
];
function newChallenge(){let q=Q[Math.floor(Math.random()*Q.length)];$("challengeQuestion").textContent=q.q;$("challengeOptions").innerHTML="";$("challengeFeedback").textContent="";q.o.forEach(o=>{let b=document.createElement("button");b.textContent=o;b.onclick=()=>{document.querySelectorAll("#challengeOptions button").forEach(x=>x.disabled=true);if(o===q.a){b.classList.add("correct");$("challengeFeedback").textContent="✓ Correct. "+q.w;$("challengeFeedback").style.color="#1a7446"}else{b.classList.add("wrong");[...document.querySelectorAll("#challengeOptions button")].find(x=>x.textContent===q.a)?.classList.add("correct");$("challengeFeedback").textContent="À revoir : "+q.w;$("challengeFeedback").style.color="#9d3038"}};$("challengeOptions").appendChild(b)})}
$("newChallenge").onclick=newChallenge;update();newChallenge();
